### ISSUE TITLE
Atualizar imagem de fundo do logo

### ISSUE THREAD

**Issue by victorperin** [nodeschool/campinas#10]
Pessoal,
Acho que essa imagem de fundo, atrás do logo, está com baixa resolução (se você abri-la em telas 1920x1080).
Pensei em muda-la, o que vocês acham?
Tive umas idéias e pesquisei umas imagens que podem substitui-la:

Original (resolução maior):
![original](http://encontreiomeuimovel.com.br/wp-content/uploads/2015/05/Campinas-Lagoa-do-Taquaral-blog.ondehospedar.com_.br-.jpg)

Antiga estação ferroviária:
![estacao](https://upload.wikimedia.org/wikipedia/commons/1/1a/Esta%C3%A7%C3%A3o_ferrovi%C3%A1ria_-_centro_cultural_de_Campinas_001.jpg)
![estacao](http://golegula.com/wp-content/uploads/2015/06/GoleGula_Boteco_na_Esta%C3%A7%C3%A3o_Junho_2015_Campinas_SP_01.jpg)

Unicamp:
![66539](https://cloud.githubusercontent.com/assets/5847145/9984486/ba1c6296-5fee-11e5-8721-a7676d10673c.jpg)

**Comment by MiattoRocha** [comment]
eae @victorperin realmente precisamos alterar algumas coisas no site, eu gostei da foto da Unicamp, acho que seria o ideal acertar a identidade visual do site pra se adequar as cores do novo logotipo escolhido pela votação no primeiro nodeschool.

Como uma outra idéia eu surgiro uma foto do próprio castelo, precisaria de uma foto com melhor resolução, mas a idéia é que o logo ficasse bem em cima do castelo. O que vocês acham?

![castelo](https://cloud.githubusercontent.com/assets/5280302/9993061/1ad7f5ca-604c-11e5-9dcc-d873549ccb4f.jpg)

**Comment by iamfelipemattos** [comment]
eu curti essa img @MiattoRocha :+1:

**Comment by fmoliveira** [comment]
Curti muito a foto da UNICAMP @victorperin , e tbm achei massa a ideia do @MiattoRocha de usar a foto da própria torre do castelo sobrepondo a torre da foto por nosso logotipo.

Vamos fazer uns testes com ambos para ver qual fica mais legal. :smiley: 

Também precisamos incluir uma borda branca em torno do logotipo para destacá-lo em meio à imagem de fundo, pois ele está bem perdido.

A observação do @MiattoRocha sobre adequarmos as cores de links e botões para a cor primária do nosso logo também é super válida.

**Comment by victorperin** [comment]
Eu gostei bastante da ideia do castelo também, mas não consegui achar nenhuma imagem de alta resolução. Se alguém encontrar, por favor, posta ai! :)

**Comment by lenamiroux** [comment]
![castelohoje_rogerio_capela](https://user-images.githubusercontent.com/12610282/31568159-48340f64-b049-11e7-8986-9ab9a8ded491.jpg)
Foto do **Rogério Capela** que pode ser utilizada com alteração e sem fins comerciais. Acho que só de emaecer para destacar a logo de vcs já é alteração o suficiente. Vou alterar aqui.

**Comment by lenamiroux** [comment]
Acredito que vcs podem utilizar a padronagem do piso de pedras portuguesas como elemento de fundo e inspiração para palheta de cores. Aqui em foto do Hugo Chinaglia no Flickr, again Creative Commons.
Also issue #15 
![padrao_hugochinaglia-med](https://user-images.githubusercontent.com/12610282/31568384-7747fbf2-b04a-11e7-9a9d-4b95cfe25ba0.png)

**Comment by victorperin** [comment]
@lenasimoes essa foto do Rogério realmente é muito boa, acho que podemos usa-la.

Gostei também das cores, vai facilitar em muito a reformulação do site.

**Comment by victorperin** [comment]
O que vocês acham?

![castelo-escurecida](https://user-images.githubusercontent.com/5847145/31681224-608e18a2-b355-11e7-8433-2d1775998856.jpg)

![image](https://user-images.githubusercontent.com/5847145/31681323-b01f4cc4-b355-11e7-8147-4aadb9e6e52d.png)

**Comment by MiattoRocha** [comment]
@victorperin ficou bem legal a imagem de fundo do site, eu acho que representa melhor a cidade do que a anterior.
Pra mim, pareceu até um balãozinho (desses de conversa em HQ) saindo do Castelo.
Não sei se foi a ideia, mas achei bem legal.

**Comment by avantikasharma** [comment]
![3bb3d0f53b1860ce7230c91402d133c7](https://user-images.githubusercontent.com/33115340/32048660-dd995e74-ba67-11e7-851b-0c409c9977a9.jpg)


Won't this be great? It represents the entire world as a whole when it comes to coding.....and maybe that would be awesome!

**Comment by victorperin** [comment]
Beleza galera mergeado, mas se alguém achar necessário mudar, cria um novo issue. :)
