### ISSUE TITLE
Fotos do último Meetup

### ISSUE THREAD

**Issue by MiattoRocha** [nodeschool/campinas#14]
Adicionei o nosso último evento ao site que precisava de uma atualização. Só que eu precisaria da foto em grupo para terminar a modificação, alguém tem a foto?
Se eu me lembro bem, foi você que tirou né, @fmoliveira ?

**Comment by fmoliveira** [comment]
Sim fui eu. Ainda bem que vc comentou do assunto, tinha esqueci completamente das fotos!

Já descarreguei do celular, vou otimizá-las e postar no Meetup, aí vc poderá pegá-las de lá! :)

**Comment by fmoliveira** [comment]
Adicionei no Facebook: https://www.facebook.com/media/set/?set=a.449946918548137.1073741834.292640207612143&type=3

O upload está super lento no Meetup, vou tentar enviar novamente durante esta semana. :wink: 

Valeu!

**Comment by victorperin** [comment]
Boa! :)
