### ISSUE TITLE
Reformulação do site

### ISSUE THREAD

**Issue by fmoliveira** [nodeschool/campinas#15]
Pessoal, lembram do assunto da issue #4 sobre a reformulação do site?

Revivendo os assuntos que deixamos para resolver mais tarde, eu fiz um rabisco no Plnkr sobre uma ideia para um novo formato para o site e gostaria de opiniões.

Algumas considerações:
- A ideia é tornar o site mais útil, fornecendo links para materiais de estudo (que podem ser workshoppers, artigos bacanas, e dicas rápidas), e também mais dinâmico, com um blog estático que permitiria a todos da comunidade contribuirem através de pull requests.
- O formato do layout, com menu lateral, não é mandatório. É apenas o meu primeiro rabisco. Se tiverem ideias completamente diferentes, postem-nas aqui para discutirmos.
- Não precisamos utilizar Bootstrap, utilizei justamente só para fazer um rabisco.

Link: http://embed.plnkr.co/kCfc06VyhLYlCjFWi8XQ/

O que vocês acham da ideia? Considerem que eu sou péssimo em design, por isso uso Bootstrap para os rabiscos kkk. Se gostarem da ideia do layout podemos pedir ajuda de alguém para deixá-lo mais bonito.

Valeu!

cc. @nodeschool/campinas

**Comment by egonyuri** [comment]
Filipe e galera,

Achei a proposta de layout bem bacana. Eu tenho uma única ressalva com
relação a organização do blog. Como sou novo no grupo não sei quais são as
intenções do grupo com o blog, se é postar uma grande quantidade de
conteúdo para atrairmos olhares dos desenvolvedores de Node em Campinas ou
se a intenção é simplesmente acrescentar a base de conhecimento de todos,
mas em ambos os casos sugiro que pensemos em alguma organização para o blog
que seja diferente de uma organização por data, acrescentando tags aos
assuntos ou também separando as informações em grupo de conteúdo maiores,
como um link para artigos, outro para dicas rápidas e outro para
workshoppers.

Att

**Comment by iamfelipemattos** [comment]
Fala pessoal, to tão distante de vocês ultimamente ): mas digo que estou me ajeitando para voltar como antes.

sobre a proposta do @egonyuri, acho um ótimo ponto que foi tocado, sendo assim, podemos pensar no jekyll para este caso.

o que acham?

**Comment by victorperin** [comment]
Boa @egonyuri.
Acho que sou o pior cara para falar de design, mas gostei da idéia.
Também acho que o jekyll para esse caso seria perfeito, @IAMFELIPEMATTOS.

**Comment by fmoliveira** [comment]
Massa! Que legal que vcs curtiram a ideia! :smiley: 

Boa @egonyuri , a ideia realmente é acumular conhecimento de toda comunidade envolvida ou que quer se envolver no NodeSchool, seja de Campinas ou não, então realmente as tags serão bem-vindas! :+1: 

@IAMFELIPEMATTOS @victorperin Jekyll com certeza é uma ótima solução para este caso!

Sobre o design, realmente acho que não faz muito sentido a gente gastar muitos neurônios nisso... Um design básico e funcional deve nos atender bem. :sunglasses: 

Só estou meio enjoado de Bootstrap, e vcs? Pensei em usar o [Semantic UI](http://semantic-ui.com/usage/layout.html) ou algum outro.

**Comment by fmoliveira** [comment]
Será que rola usarmos algum framework frontend com flexbox? A compatibilidade já está bem ampla, só não vai funcionar legal em IE porque ainda tem muitos bugs. Fora isto, todos os browsers majoritários já suportam bem: http://caniuse.com/#feat=flexbox

Segundo estatísticas do Can I Use, 91% dos navegadores usados por brasileiros já suportam esta função plenamente.

Para o IE podemos colocar um alerta recomendando o uso de outros navegadores. Como se trata de uma comunidade de hackers, não vejo problemas em fazer isso. E vcs o que acham?

Alguns frameworks com flexbox:
- http://bulma.io/
- http://flexboxgrid.com/

Nenhum motivo especial para isto, apenas aprendizado mesmo. :wink:

**Comment by lnfnunes** [comment]
Particularmente não vejo necessidade dum framework para montar o layout, mas isso é só gosto pessoal.
Deixo aqui uma dica que acho muito boa com relação a flexbox:
https://philipwalton.github.io/solved-by-flexbox/

O cara já da mastigado as soluções para problemas bem comuns.
abs

**Comment by fmoliveira** [comment]
@lnfnunes  Infelizmente eu ainda sou bem dependente de frameworks, pois sou bem fraco em UI. Mas você tem razão com certeza. :wink: 

Frameworks frontend são legais para começar um projetinho bem rápido, e este é o único motivo para eu gostar deles. Mas quando vc vê sites iguais por todo lado, realmente é bem enjoativo. Sem contar os tantos KBs de assets que você nunca usa e fica degradando desempenho do site.

Acho super válido fazermos sem framework frontend, mas um fato é que eu iria penar para fazer um trabalho bonito sem framework. Se tiver alguém para dar uma força eu voto em fazermos sem framework com certeza!

Vou estudar esse link, valeu!

Abs! :smiley:

**Comment by fmoliveira** [comment]
Estou brigando com o layout para o novo site, sem frameworks frontend. Estas dicas de flexbox são sensacionais @lnfnunes !

Ainda não está legal, principalmente porque acho super difícil trabalhar com layouts verdes, mas, segue o progresso: https://fmoliveira.com.br/nodeschoolcps/

Críticas e sugestões são super bem vindas!

**Comment by lnfnunes** [comment]
Q legal @fmoliveira! Bacana ver que está conseguindo aprender o conceito...
Pra quem já estava acostumado com um esquema, num primeiro momento Flexbox são meio malucos, mas o esquema é desapegar e aprender como se fosse do zero, aprendendo o conceito fica tranquilo!

Não entendi a parte do "difícil trabalhar com layouts verdes"... hehehe

**Comment by fmoliveira** [comment]
@lnfnunes auhahuahuuhahua. Eu tenho muita dificuldade para formar paletas de cores, e verde para mim é uma das mais difíceis, não sei porque... curto demais trabalhar com paletas azuis e roxas, parece mais natural fazer um layout bonito com elas.

De qualquer forma, peguei umas dicas com um UI Designer aqui do trampo, ele me deu umas dicas sobre as teorias das cores do Adobe Kuler que vão ajudar demais, já tive algum progresso. Dei uma leve saturada no logo do NodeSchool Campinas para deixar as cores mais vivas.

Realmente, desapegar de frameworks é tudo de bom! De um mês pra cá tenho trabalhado bastante em desapegar do Bootstrap, e estou curtindo demais o resultado. Vou continuar avançando neste layout do NodeSchool e vou atualizando o post aqui... :smiley:

**Comment by fmoliveira** [comment]
@lnfnunes auhahuahuuhahua. Eu tenho muita dificuldade para formar paletas de cores, e verde para mim é uma das mais difíceis, não sei porque... curto demais trabalhar com paletas azuis e roxas, parece mais natural fazer um layout bonito com elas.

De qualquer forma, peguei umas dicas com um UI Designer aqui do trampo, ele me deu umas dicas sobre as teorias das cores do Adobe Kuler que vão ajudar demais, já tive algum progresso. Dei uma leve saturada no logo do NodeSchool Campinas para deixar as cores mais vivas.

Realmente, desapegar de frameworks é tudo de bom! De um mês pra cá tenho trabalhado bastante em desapegar do Bootstrap, e estou curtindo demais o resultado. Vou continuar avançando neste layout do NodeSchool e vou atualizando o post aqui... :smiley: 

Valeu pelo feedback! :wink:

**Comment by lnfnunes** [comment]
Me parece que essa issue foi resolvida no pull #20.
Estão precisando de alguma ajuda ainda ?

**Comment by victorperin** [comment]
@lnfnunes qualquer ajuda é bem vinda.
O @guiluchesi deu uma boa melhorada no visual atual, mas todos os itens que estão sendo discutidos aqui continuam em aberto.

Com relação ao layout do @fmoliveira eu gostei principalmente da área do próximo evento e canais. Talvez o esquema de cores que o @guiluchesi usou possa melhora-lo.

Atualmente, o que eu acho que precisamos fazer para finalizar essa issue:
- [ ] Layout superior (Onde tem informações do próximo evento e canais da comunidade)
- [ ] Jekyll (Isso inclui componentizar melhor a pagina, atualmente estamos com tudo no index.html)
- [ ] Menu

PS: ainda temos a issue #10 também :stuck_out_tongue:

**Comment by luchesigui** [comment]
Foi mal pessoal, nem me atentei que já estava rolando uma reformulação grande no site. Vi que tava meio ruim algumas coisas e tentei corrigir do melhor jeito que pude na estrutura que tinha.

Quanto as cores, usei aquela paleta de cores porque já era o que estava sendo usado no logo.
Talvez o ideal fosse azul escuro e ouro, que são as cores da nossa cidade e o ouro continua sendo a cor do nodeschool o/

Nesse novo layout que o @fmoliveira ta fazendo, em uma olhada rápida assim, talvez fizesse os seguintes ajustes (anexo).

![cores](https://cloud.githubusercontent.com/assets/5860206/23507902/ef79591e-ff2d-11e6-98dc-4b6a096518a4.jpg)

**Comment by victorperin** [comment]
Galera, eu estava dando uma fuçada e gostei desse layout [NodeSchool - San Francisco](https://nodeschool.io/sanfrancisco/)

**Comment by victorperin** [comment]
Galera, vou fechar essa issue pois vou começar a migrar as coisas que temos no trello para issues do github e centralizar toda a organização por aqui.
