### ISSUE TITLE
1º NodeSchool Campinas

### ISSUE THREAD

**Issue by fmoliveira** [nodeschool/campinas#2]
**Edição de 07/07/2015:**

Atenção!

As inscrições para o 1º Nodeschool Campinas estão abertas. O meetup será realizado no dia 31/07/2015 das 19:30hs as 22:30hs na Princi Web, próxima a Lagoa do Taquaral.

Corra e garanta já a sua vaga: http://www.meetup.com/Nodeschool-Campinas/events/223778257/

---
**Postagem original:**

Em primeiro lugar, eu gostaria de dar as boas vindas a todos que estão lendo este tópico! Aqui nós iremos planejar o primeiro NodeSchool da cidade de Campinas. Para quem ainda não conhece o NodeSchool, recomendo acessar o nosso site em http://nodeschool.io/campinas/ e o site oficial do NodeSchool em http://nodeschool.io/.

Os detalhes do evento ainda estão sendo decididos. O ingresso será cobrado, porém, o evento não tem fins lucrativos, o que minimiza bastante o preço do ingresso, visto que ele será voltado a cobrir os custos do evento. Assim que tivermos estes detalhes definidos, iremos divulgá-los a todos vocês.

Todos que estiverem em Campinas e região, e tiverem interesse em participar do 1º NodeSchool Campinas, por favor comentem neste tópico e se apresentem.

Segue uma sugestão de roteiro para vocês se apresentarem:
- Nome? Idade?
- Há quanto tempo começou a programar?
- Qual a sua linguagem de programação favorita? Qual o seu nível de intimidade com ela?
- Já desenvolveu em Node.js? Qual o seu nível de intimidade com a plataforma?

Queremos conhecer melhor todos vocês para que o evento possa atender bem o maior número de participantes.

Peço que divulguem o site do evento e o repositório a todos seus colegas de faculdade, colegas de trabalho, e amigos programadores. Vamos agitar o cenário JavaScript de Campinas!

**Comment by adahox** [comment]
tenho mt interesse tbm.

**Comment by fmoliveira** [comment]
Olá Caio e Adão, obrigado pelo contato e pelo interesse! Muito bom saber que já tem gente ansiosa pelo evento! Nós também estamos, e muito!

Eu acabei de editar o primeiro post com um roteiro para apresentação de todo mundo. Vocês poderiam por favor postar um novo comentário lhes apresentando conforme o roteiro?

Valeu pessoal! Em breve mais detalhes!

**Comment by adahox** [comment]
Ola, 
Me chamo Adão, tenho 24 anos. Desde os 16 programando. Minha linguagem preferida é o php. tenho conhecimentos avançados em php. comecei a me interesar pelo node.js faz pouco tempo. ainda não instalei e comecei a usa-lo. porem tenho conhecimento em javascript e frameworks. quanto ao node acredito que sera fácil.

**Comment by BielRibeiro** [comment]
Salve!
Meu nome é Gabriel, tenho 24 anos. ~~Faço programas~~ Programo somente a 2 anos.
Minha linguagem favorita é o Javascript, desde que comecei tenho estudado bastante, porém ainda sou noob.
Comecei estudar NodeJS recentemente, e estou seguindo o roteiro do nodeschool.io.
Curto bastante eventos web, e fiquei muito entusiasmado com o interesse de vocês em fazer um só de node aqui em Campinas. Estou ae pra ajudar no que precisar. :metal:

**Comment by rodolfoprr** [comment]
Da hora, tenho interesse!

Meu nome é Rodolfo, tenho 25 anos e programo em C# há uns 8 anos +/-. Comecei com Node.js há alguns meses, em um projeto de sistema para clínicas de vacinação e também estou utilizando em um aplicativo mobile de cerveja.

O que vocês precisarem para o evento, é só falar! \o/

**Comment by fmoliveira** [comment]
Legal pessoal! Muito bom ver o interesse de todos vocês @adahox @caio-ps @BielRibeiro @rodolfoprr .

Sejam todos muito bem-vindos. Fiquem tranquilos pois nós precisamos de pessoas de todos os níveis de conhecimento no evento. De que adianta ter pessoas super dispostas a ensinar se não tiver também pessoas interessadas em aprender?

Obrigado pela força galera! Com certeza vamos precisar do apoio de vocês! Iremos manter-lhes informados sobre qualquer novidade.

**Comment by vitorlevi** [comment]
Olá!

Sou Vitor Levi tenho 28 anos, sou UX Designer / Prototyper e gosto de code também. Tenho conhecimentos em PHP, MySql, Firebase, NodeJS, SASS, HAML, um pouquinho de Ruby e Python.

Atualmente trabalho na Intel aqui mesmo em Campinas, no TechnoPark. Além dos projetos do dia-a-dia eu faço soluções para otimizar o trabalho do time e também gosto de fazer protótipos dos trabalhos que estou fazendo para testes. Seria bacana aprofundar mais em Node.

Abs!

**Comment by caio-ps** [comment]
Opa, boa noite!
Meu nome é Caio Sousa, eu tenho 25 anos. Trabalho com programação há pouco mais de 4 anos, e neste tempo todo estive trabalhando com Java. Tenho um bom conhecimento na plaraforma como um todo, desde o JSE, JEE, e outras extensões. Já tinha ouvido falar do nodejs através de alguns amigos programadores, e recentemente me envolvi em um projeto que utiliza a tecnologia. Tenho um conhecimento ainda básico em Javascript e nodejs, mas estou estudando forte para evoluir rapidamente.
Abraços a todos, e até o evento!

**Comment by BielRibeiro** [comment]
@fmoliveira sugiro criar um evento no meetup http://www.meetup.com/

:)

**Comment by Vinidel** [comment]
Olá,
Meu nome é Vinícius Deláscio Fortunato, tenho 29 anos. Trabalho na área  mais ou menos a 7 anos, a maior parte deste tempo trabalhando com Java, minha linguagem favorita e a que tenho um conhecimento maior. 

Ouvi falar em Node.Js mais ou menos no meio do ano passado pesquisando sobre o assunto no YouTube quando estava pesquisando sobre JavaScript server side. Felizmente algum tempo depois fui alocado em uma equipe que está desenvolvendo APIs utilizando o NodeJs. Estou aprednendo a desenvolver no Node.Js, porém, ainda sou novo na plataforma e por enquanto tenho conhecimento básico em JavaScript.
Abs.

**Comment by fmoliveira** [comment]
Sejam bem-vindos @vitorlevi @caio-ps @Vinidel ! :smiley: 

Obrigado pela sugestão @BielRibeiro ! Eu conhecia o Meetup só de nome, mas ainda não o tinha utilizado. Estou preparando o nosso grupo e em breve postarei o endereço.

**Comment by brunove** [comment]
Boa Tarde !
Meu nome é Bruno Veiga, tenho 29 anos. Trabalho com desenvolvimento de sistemas aproximadamente a 8 anos, já tive maior convívio com C, C++ e Java. Comecei recentemente a trabalhar em um projeto na empresa com o APis utilizando o NodeJs, mas sou completamente novo no assunto, por se tratar de um projeto em fase inicial temos a possibilidade de implantar todas as melhores práticas e estou procurando locais onde posso evoluir meu conhecimento para somar nesse novo desafio.

Abraços a todos !

**Comment by fmoliveira** [comment]
Pessoal segue abaixo o link de nosso grupo no Meetup. Assim que tivermos a definição da data e local iremos atualizar o grupo e o repositório.

http://www.meetup.com/Campinas-Nodeschool/

**Comment by fmoliveira** [comment]
Legal @brunove! Seja bem-vindo ao grupo! :smile:

**Comment by marceloMoro** [comment]
Boa tarde!

Meu nome é Marcelo Moro SIlva, tenho 32 anos.
Tenho experiência de 7 anos como programador Java e SQL. Atuei em projetos para Web utilizando frames de mercardo, tais como Struts, Hibernate, JPA e Java Server Faces.
MInha preferência é Java. Sou programador com certificado OCPJP (Oracle Certified Java Programmer) para Java 6.
Minha experiência com Node é acadêmica (básico). Conheço muito pouco. Atualmente, trabalho em uma instituição financeira, em um projeto de implementação de APIs para acesso a serviços. Pretende me especializar nesta tecnologia.

Muito obrigado pela oportunidade.
Abs,
Marcelo Moro

**Comment by fmoliveira** [comment]
Seja bem-vindo @marceloMoro ! Muito bom! Tenho certeza que você vai se familiarizar rapidamente com Node.

O começo do ano foi bem corrido para mim, mas logo trarei novidades sobre o evento para vocês!

Abraços a todos!

**Comment by fmoliveira** [comment]
Seja bem-vindo @marceloMoro ! Muito bom! Tenho certeza que você vai se familiarizar rapidamente com Node.

Este ano já começou super corrido, graças a Deus é correria boa, mas logo eu trarei novidades sobre o evento para vocês!

Abraços a todos!

**Comment by fabianosb** [comment]
Uhuu sou iniciante ,, consigo acompanhar ? posso participar ?? quero aprender .. tomar um rumo na vida, rsrsrs

**Comment by Mephisto07** [comment]
Olá!
Me chamo Nicolas, tenho 22 anos e sou de São Paulo. 
Programo oficialmente desde os 17 anos, mas sei HTML puro desde meus 12. Hoje, desenvolvo em ASP.NET Web API, mas já estive em projetos em ASP 3.0 e Java (J2EE, Struts, Hibernate, etc).
Eu gosto mesmo é de desenvolver em Javascript e suas milhões de APIs rs. Creio que juntamente com C#, é a linguagem que tenho mais facilidade e que trabalho há mais tempo.
Gostaria de aprender e conhecer melhor o Node.JS, muitos projetos estão utilizando, principalmente fora do Brasil.

Aguardo o nosso NodeSchool!!!

Grande abraço a todos!

**Comment by fmoliveira** [comment]
Olá @fabianosb , seja bem-vindo!

O NodeSchool é um evento voltado a programadores de todos os níveis, desde iniciantes a veteranos.  Os programadores serão divididos em grupos de acordo com o seu nível de conhecimento e receberão a instrução necessária para os seus devidos níveis.

É claro que é muito útil chegar com um pouco de experiência em lógica de programação, mas, isto não será impeditivo para o seu desenvolvimento. :)

Abraços!

**Comment by fmoliveira** [comment]
Olá @Mephisto07 , seja bem-vindo!

Boa! Minhas linguagens preferidas também são C# e JS. :smile: 

Estamos preparando a estrutura do evento e em breve iremos anunciar a data e o local. Muito obrigado a todos pelo apoio de participarem de nosso repositório no GitHub e estarem no aguardo do evento!

Grande abraço a todos!

**Comment by fmoliveira** [comment]
Olá @Mephisto07 , seja bem-vindo!

Boa! Minhas linguagens preferidas também são C# e JS. :smile:
Node.JS ainda não ganhou tanta força no Brasil quanto já tem fora dele, mas realmente tem muito mais potencial do que eu imaginava antes de conhecê-la.

Muito bom ver o pessoal de Sampa se interessando no NodeSchool Campinas! ;)

Estamos preparando a estrutura do evento e em breve iremos anunciar a data e o local. Muito obrigado a todos pelo apoio de participarem de nosso repositório no GitHub e estarem no aguardo do evento!

Grande abraço a todos!

**Comment by fmoliveira** [comment]
Olá @Mephisto07 , seja bem-vindo!

Boa! Minhas linguagens preferidas também são C# e JS. :smile:
Node.JS ainda não ganhou tanta força no Brasil quanto já tem fora dele, mas realmente tem muito mais potencial do que eu imaginava antes de conhecê-la.

Muito bom ver o pessoal de Sampa se interessando no NodeSchool Campinas! ;)

Estamos preparando a estrutura do evento e em breve iremos anunciar a data e o local. Muito obrigado a todos pelo apoio ao participarem de nosso repositório no GitHub e estarem no aguardo do evento!

Grande abraço a todos!

**Comment by limaleeo** [comment]
Olá!!
Sou o Leonardo, 21 anos e Analista de Sistemas Jr no UOL na área de P&D.
Programo há +/- 2 anos profissionalmente.
Minha linguagem favorita é Java e possuo conhecimento avançado, porém tenho contato diariamente com diversas outras tecnologias e agora estou iniciando em um projeto em Node.js 
Meu conhecimento em Node ainda é básico.
Me coloco a disposição para colaborar com o evento.

**Comment by fmoliveira** [comment]
Olá @limaleeo , seja bem-vindo!

Eu comecei com Node.js por ter caído de paraquedas em um projeto meu que eu mesmo determinei que seria em Node.js, se não acho que eu estaria enrolando até hoje para começar kkk. E deu certo!

Com certeza vamos precisar de gente para colaborar com o evento. Obrigado pela disposição!

Abraços.

**Comment by wilsonck** [comment]
Meu nome é Marcelo Wilson, tenho 32 anos.
Trabalho a mais de 10 anos com web, atualmente trabalho como Front, mexendo basicamente com Javascript. 
Meu conhecimento em Node ainda é básico.
Me coloco a disposição para colaborar com o evento.

Obrigado pela oportunidade.

**Comment by IAMFELIPESOUZA** [comment]
yo guys!

**Comment by dmstole** [comment]
Fala Galera, tudo bem?

O meu nome é Diogo Miranda (Tiozão) e tenho 34 anos. Depois de ter trabalhado com geoprocessamento durante 10 anos resolvi ingressar na área de desenvolvimento de sistemas web, onde estou à um pouco mais de 7 anos. Sou fascinado por desenvolvimento e testes, tudo que eu penso sempre é baseado por testes. Sobre o Node, bem... acontece que estou iniciando e confesso que tenho me dedicado a aprender sobre esta tecnologia. Caso alguém tenha interesse, poderiam me passar links, pdf, demos, tudo que puder agregar aos meus estudos. Ficarei eternamente grato.

Grande abraço. ;p

**Comment by adamsalves** [comment]
Olá pessoal, tudo certo?

Meu nome é Adams, trabalho faz 4 anos com web programando em PHP e agora estou estudando Node.js. Me deparei com Node nos estudos sobre javascript e AngularJS. Estou disposto a ajudar no evento também. Abraço

**Comment by fmoliveira** [comment]
Olá pessoal,

Sejam muito bem-vindos @wilsonck , @IAMFELIPESOUZA , @dmstole e @adamsalves !

É muito gratificante ver o interesse de todos. A pedido do @dmstole vou incluir em nossa wiki aqui no GitHub mesmo alguns links de materiais interessantes de Node.js.

Como já estamos com bastante gente interessada, está mais fácil negociar um espaço para realização do evento. Ainda este mês irei lhes trazer novidades!

Abraços a todos.

**Comment by arielhsn** [comment]
Ola,

Meu nome é Ariel, tenho 23 anos, começei a programar em 2011, a minha liguangem de programação favorita é java, porém já trabalhei com C# durante 2 anos e também gostei da experiencia que tive, voltando para o java, estou trabalhando com ela há 2 anos e me considero de nivel pleno, ainda não desenvolvi nenhuma aplicação em node.js, entretanto estou em busca de conhecimento dessa tecnologia que me parece muito promissora.

**Comment by IAMFELIPESOUZA** [comment]
@fmoliveira de uma olhada no seu gtalk!

**Comment by dmstole** [comment]
Valeu Felipão... você é o cara!

Abraços.

Diogo A. Miranda
Especialista em Sistemas Web
(12) 98166-7106

Date: Wed, 6 May 2015 19:09:41 -0700

**Comment by edantasdias** [comment]
Quero participar, me chamo Edilson tenho 27 anos e programo a 3 anos. Minha linguagem favorita é o php.

**Comment by fmoliveira** [comment]
Sejam bem-vindos @arielhsn e @edantasdias !

Ok @IAMFELIPESOUZA , irei olhar!

Sou nada @dmstole kkk. No fim de semana eu já coloco os links para você ir se divertindo! :)

**Comment by edantasdias** [comment]
Pode me dizer qual a data do evento?

**Comment by dinho19sp** [comment]
E ai pessoal, blz,

A ideia de vocês é muito interessante, por isso estou aqui e afim de aprender muito sobre node.js

Meu nome é Francisco Nascimento
Tenho 40 anos ,trabalho como analista desenvolvedor web com linguagem PHP nível já avançado, trabalho com PHP desde meados de 2007,  tenho uma boa noção de javascript, e meu interesse é aprender muito sobre node.js, pois hoje estou sendo solicitado a desenvolver aplicações que funcionem em tempo real, e pelo o que pesquisei o node.js é um dos mais indicados, porem não tive a oportunidade de usa-lo, e acredito que aqui vai ser a meu primeiro contato com ele e espero absorver muita coisa.. é isso ai.. rsrsrs

abraços a todos..

**Comment by fmoliveira** [comment]
@edantasdias , a data ainda não está definida pois primeiro estávamos buscando público. Os próximos passos são recrutar os interessados de nível mais avançado para ajudar na mentoria e agendar o local e data. Acredito que consigamos realizar o evento em junho, vou notificar todos com pelo menos uns 20 dias de antecedência.

Vamos cobrar um valor simbólico para podermos fazer um lanche no evento. Logo divulgaremos este valor também! :smiley:

**Comment by fmoliveira** [comment]
Olá @dinho19sp , seja bem-vindo!

Node.js realmente atende aplicações em tempo real muito bem. Como você já se dá bem com JavaScript, trabalhar com Node.js será bem tranquilo! :+1: 

Valeu, abraços!

**Comment by ThePanuto** [comment]
Olá!

Meu nome é Bruno Luis, tenho 20 anos  e trabalho com programação a +/- 3 anos. A minha plataforma de escolha é a Web, e a minha linguagem de escolha é JavaScript. Flerto e muitas vezes prefiro backend, mas consigo me virar bem no frontend também. Ao mexer com backend, minha escolha primária é o NodeJS. Mexo e reviro o NodeJS de cabeça pra baixo, desde o source até as API's.

Com NodeJS, já desenvolvi API's REST em projetos de consumo próprio, sites usando Express (e sem usar), apps desktop usando Electron e vários outros projetos menores.

O evento ainda está de pé? Já temos alguma data? Estou muito interessado em participar.
Abraços!

**Comment by MiattoRocha** [comment]
@ThePanuto, seja bem vindo!
Como o @fmoliveira falou ainda não temos data defiida, mas deverá ser em junho o nosso primeiro evento. Tanto aqui no GitHub quando a página do meetup está com um número de interessados muito bom e já é mais fácil conseguir um local para o evento.

Estou ansioso também pelo evento, olhando o perfil dos interessados aqui, será um evento de alto nível.

**Comment by ThePanuto** [comment]
@MiattoRocha depois que mandei a mensagem que li as conversas, kkk mas obrigado.
Caso necessitem de alguma ajuda, podem falar comigo.

**Comment by fmoliveira** [comment]
Valeu @ThePanuto ! Com certeza vamos precisar de sua ajuda sim. ;)

**Comment by dpcamargo** [comment]
Me chamo Dario e tenho 31 anos. Programo em LabVIEW faz uns 8 anos e estou procurando outras linguagens para algumas coisas que o labview deixa a desejar.

**Comment by leotorati** [comment]
Olá! Tenho interesse em participar.
Atualmente programo em PHP em projetos Drupal, mas estou ingressando no mundo do Node.js.
Att,

**Comment by brunobelarmino** [comment]
Olá,

Me chamo Bruno Belarmino, tenho 30 anos e programo a uns 8 anos. Poliglota, codo em java, c#, JS e um pouco de c++.

Conheço node desde o começo em 2009, mas tenho tenho usado ele diariamente de uns 2 anos pra cá.

Atualmente tenho trabalhado com mobile voltado para Android codando na plataforma nativa e hibrida com Córdova e claro NodeJs. Alem disso tenho investido bastante em evangelização do nodejs, através de coachs, consultorias e palestras.

Gostaria muito de contribuir com o evento.

**Comment by fmoliveira** [comment]
Sejam bem-vindos @dpcamargo  e @leotorati !

Muito legal que estejam interessados. :)

**Comment by fmoliveira** [comment]
Seja bem-vindo @brunobelarmino !
Ótimo, com certeza vamos precisar da sua ajuda, e ela será de grande valia!

Muito obrigado pelo contato e pela disposição!

Vou enviar um email a todos que se demonstraram interessados em contribuir com o evento para conversarmos.

**Comment by fmoliveira** [comment]
@brunobelarmino @nubunto @IAMFELIPEMATTOS @rodolfoprr @MiattoRocha 

Convidei todos vocês à board de organização do Nodeschool Campinas no Trello. Caso vocês não tenham recebido o convite, pode ser erro de digitação do email de vocês, neste caso, por favor me avisem para que eu reenvie.

Caso haja mais alguém interessado em ajudar na organização ou mentoria do evento, me escreva para conversarmos.

Em breve mais novidades.

Abraços a todos!

**Comment by igorTavares** [comment]
Fala galera!

Me chamo Igor Tavares e desenvolvo para sistemas embarcados a 5 anos. Tenho bem pouco XP com web, mas já utilizei node para desenvolver uma feature em um projeto em que participei e gostei bastante.

Também quero participar dos eventos!

**Comment by fmoliveira** [comment]
Valeu @igorTavares , seja bem-vindo! ;)

**Comment by fmoliveira** [comment]
Bom dia pessoal!

Ontem nós realizamos a 1ª reunião de organização do Nodeschool, e vocês podem ler a nossa ata de reunião na íntegra em: https://github.com/nodeschool/campinas/blob/master/diario-de-bordo/2015-07-02_1a-reuniao-de-organizacao.md

Vamos abrir a votação de data no meetup, em seguida atualizo aqui para que todos vocês possam votar.

Abraços!

**Comment by edersonnascimento** [comment]
Bom dia a todos,

A maioria de vocês não me conhece ainda, não fui à primeira reunião, mas
estou acompanhando o mais de perto possível tudo o que está sendo feito.

Fiz uma pesquisa rápida e descobri que em Campinas existe um Conselho
Municipal de Ciência, Tecnologia e Inovação. Além disso lendo um trecho da
ata da última reunião e na página 2, item 3 eles discutiram sobre a Semana
da Ciência, Tecnologia e Inovação de Campinas (SCTIC 2015) a ser realizada
de 19 a 25/10/2015 . Nesta discução foi apresentada a seguinte proposta:

"...

> *Envolver  todos os  atores  de  uma  “quádrupla  hélice” (empresas,
> governo,  universidade  e  sociedade  civil organizada),  sendo  que  cada
> um  possa contribuir com sua programação individual em torno de uma única
> identidade; ii) A Prefeitura e a Câmara deverão atuar como agentes de
> integração e divulgação da programação através de seus veículos  de
> comunicação  (rádio,  TV  e  portal)  e  iii)  Fazer  do  CMCTI  o  fórum
> da  organização  do evento, onde contribui quem desejar através de um
> processo de construção coletiva e orgânica*
>
..."

Talvez seja um apoio importante para o NodeSchool Campinas.

Abraço,
Éderson

2015-07-03 0:23 GMT-03:00 Filipe Oliveira <notifications@github.com>:

**Comment by edersonnascimento** [comment]
ah, seguem os links:

http://www.campinas.sp.gov.br/governo/desenvolvimento-economico/conselho-ciet.php
http://www.campinas.sp.gov.br/arquivos/desenvolvimento-economico/cmcti_8a_ata_ordinaria_20150508.pdf

2015-07-03 11:43 GMT-03:00 Éderson C. do Nascimento <
ederson.nascimento@gmail.com>:

**Comment by nubunto** [comment]
legal @edersonnascimento, muito interessante! tenho certeza de que o evento pode se beneficiar da informação

**Comment by fmoliveira** [comment]
Atenção!

As inscrições para o 1º Nodeschool Campinas estão abertas. O meetup será realizado no dia 31/07/2015 das 19:30hs as 22:30hs na Princi Web, próxima a Lagoa do Taquaral.

Corra e garanta já a sua vaga: http://www.meetup.com/Campinas-Nodeschool/events/223778257/

**Comment by fmoliveira** [comment]
O evento foi um sucesso! Confiram fotos em: http://www.meetup.com/Nodeschool-Campinas/photos/26306043/

Parabéns a todos os mentores e muito obrigado a @princiweb e @rodolfoprr  pelo espaço e pelo coffee break.

Fiquem atentos para o próximo meetup!
