### ISSUE TITLE
WorkShop: Material de Apoio

### ISSUE THREAD

**Issue by milesibastos** [nodeschool/campinas#21]
Olá Pessoal!
Estou escrevendo um série de _posts_ com a intenção de criar um material de apoio em português para os eventos e gostaria muito do _feedback_ de vocês.

Segue o link:
https://medium.com/devexpert/nodeschool/home

thread iniciada em: https://github.com/nodeschool/rio/issues/9

**Comment by victorperin** [comment]
Parabéns pelo material @milesibastos, a comunidade nodeschool está precisando muito disso! :)
Eu dei uma lida rapida aqui, mas assim que tiver um tempo, de passo um feedback do que seria legal melhorar.
