### ISSUE TITLE
Hacktoberfest 2017

### ISSUE THREAD

**Issue by victorperin** [nodeschool/campinas#23]
- [x] Criar label "Hacktoberfest"
- [ ] Criar issues que guiem a comunidade a contribuir
- [ ] Evento #25 

Quem quiser ajudar com isso, é só abrir issues.

**Comment by lnfnunes** [comment]
Com essa dica acho que daria pra fechar a task 2 ?
- [ ] Criar issues que guiem a comunidade a contribuir
![image](https://user-images.githubusercontent.com/2450417/31237611-d36d653a-a9cd-11e7-815c-85c73403e938.png)

E com o [comentário](https://github.com/nodeschool/campinas/issues/25#issuecomment-334504212) do @MiattoRocha na issue #25 daria pra fechar a task 3 ?
- [ ] Evento #25

**Comment by victorperin** [comment]
1- A idéia é criar novas issues, com a tag hacktoberfest.

2- Vamos ter uma versão a mais também. Principalmente porque o LHC tem pouco espaço.
A idéia de criar o evento dia 28, continua de pé.

**Comment by MiattoRocha** [comment]
Pensei aqui em fazer uma Landing page do Nodeschool Campinas, coletando números que já alcançamos, algumas métricas legais, etc...
Para ajudar a conseguir locais para os eventos e talvez alguns apoios para projetos maiores.
Talvez essa ideia pudesse gerar algumas tarefas para o Hacktoberfest.
O que vocês acham?

**Comment by victorperin** [comment]
Booooa!

Só de criar essas issues, já é um avanço. :)
