### ISSUE TITLE
Meetup: Hacktoberfest 2017

### ISSUE THREAD

**Issue by victorperin** [nodeschool/campinas#25]
Pessoal, tenho a intenção de criar um Meetup focado no Hacktoberfest. O que acham?

Para organizar um evento foda, o pessoal da digital ocean preparou um event kit aqui: https://hacktoberfest.digitalocean.com/eventkit

Pensei em fazer a discussão nessa issue e vou atualizando essa descrição, conforme entrarmos em concenso.

## Data e Local
Ainda não temos certeza sobre isso, mas estamos pensando em:
Dia: 28/10 (manhã e tarde) (não confirmado)
Local: InGaia Campinas (não confirmado)

## Possível agenda
Parte da manhã:
- Boas vindas (tempo para o pessoal chegar/se organizar)
- Mini Talk: O que é o Hacktoberfest e como funciona?
- Talk: Introdução ao Open Source
- Workshop: como contribuir para repositórios Open Source

Pausa para o almoço

Parte da tarde:
- Hacktime organizado em equipes

**Comment by notnotgabriel** [comment]
Tope! Quero participar \o/

**Comment by gvillalta99** [comment]
Eu também quero o/

**Comment by MiattoRocha** [comment]
Também quero participar!
O que já seria interessante preparar? 

Eu tava pensando em pegar uns materiais fáceis de introdução a GIT tipo (https://try.github.io/levels/1/challenges/1) só que em português.
Pensei em juntar bons materiais e/ou traduzir alguns dos resources que estão no link do eventkit.

Sobre a agenda, na minha opinião, seria legal uma definição de grupo e possíveis desafios antes do almoço, pra ter um tempo do grupo conversar entre eles.

Também estou querendo ouvir um pouco mais de como vocês estão pensando em como será o evento.

**Comment by MiattoRocha** [comment]
Não sei se todos viram mas, já tem um evento Hacktoberfest agendado, organizado pelo LHC (Laboratório Hacker Campinas).
https://www.meetup.com/pt-BR/LabHackerCampinas/events/243804432/
Ainda tem 5 vagas até esse momento.

**Comment by fmoliveira** [comment]
Massa, acho top! 😃 
Vou ler o guia da Digital Ocean para conhecer o formato do evento e poder ajudar. ;)

**Comment by victorperin** [comment]
@MiattoRocha no ultimo nodeschool eu tinha trocado idéia com o Thiago, lá do LHC. Quanto mais eventos, melhor! :)

**Comment by ocdigital** [comment]
Show... esperando definir o local!

**Comment by victorperin** [comment]
Infelizmente não rolou galera :/
Acabei me enrolando com as coisas aqui na empresa e não consegui organizar. :(
