### ISSUE TITLE
Landing Page do Nodeschool Campinas

### ISSUE THREAD

**Issue by MiattoRocha** [nodeschool/campinas#29]
Já foram 13 meetups do Nodeschool Campinas e eu fiquei pensando, Quantas pessoas diferentes já atingimos? Por quantos locais/empresas já passamos? 
Já atingimos alguns números bem impressionantes, que tal transformar isso em uma página vitrine, para atrair mais gente, mais mídia e mais apoiadores?
Eu sugiro usar essa tarefa para discutir a idéia e centralizar as tarefas para concluir esse objetivo. Abaixo segue um check list de coisas que eu acharia importante para realizar essa página.

- [ ] Definir quais dados são interessantes para mostrar
- [ ] Levantar os dados
- [ ] Montar uma página estática para exibir esses dados 
- [ ] Pensar em estratégias para divulgar esse site da melhor forma

Coloquei alguns itens no checkbox, mas gostaria de contar com a ajuda de todos, propondo sugestões, criticando, avaliando e desenvolvendo.
Valeu!

**Comment by victorperin** [comment]
Boa @MiattoRocha! :)

Então, ja faz um tempo que precisamos reescrever a página web. Pensei em colocar isso aqui junto.
Podemos usar algumas informações da API do Meetup.com. Já fizemos isso no [comunidadescampinas/agenda-api](https://github.com/comunidadescampinas/agenda-api).

Além disso, podemos usar informações do próprio repositório, a partir da api do github.

Conforme for tento novas idéias, vou comentando aqui.

**Comment by victorperin** [comment]
Galera, vou fechar essa issue pois vou começar a migrar as coisas que temos no trello para issues do github e centralizar toda a organização por aqui.
(vou só manter a ultima em aberto, pois ela tem todas essas outras linkadas.
