### ISSUE TITLE
Reformulação do website

### ISSUE THREAD

**Issue by fmoliveira** [nodeschool/campinas#4]
Fala galera, beleza?

Precisamos dar uma reformulada no site do Nodeschool Campinas pelos seguintes motivos:
 * Melhorias no layout;
 * Esclarecer melhor o que é o NodeSchool para quem nunca ouviu falar sobre ele - isto deve ajudar a chamar a atenção de estudantes, mentores e patrocinadores;
 * Falar mais sobre os detalhes do evento, o que já fizemos, e o que vamos fazer.

Conteúdo desejado:
 * Descrição do NodeSchool;
 * Chamadas para estudantes e mentores;
 * Dados sobre os meetups passados e futuros, já em uma forma facilitada de atualização;
 * ~~Galeria de fotos~~ Uma foto por evento passado com link para o álbum no Facebook/Meetup;
 * Logotipos de parceiros e patrocinadores;
 * Links úteis (por exemplo: nodejs.org e nodeschool.io).

Segue lista de alguns que eu achei legais, para nos inspirarmos:
 * http://nodeschool.io/hamburg/
 * http://nodeschool.io/baltimore/

Quem mais tem sugestões? :smiley:

**Comment by fmoliveira** [comment]
ping @MiattoRocha

**Comment by fmoliveira** [comment]
ping @MiattoRocha

**Comment by fmoliveira** [comment]
ping @IAMFELIPEMATTOS @rodolfoprr @nubunto @brunobelarmino @edersonnascimento

**Comment by fmoliveira** [comment]
O Hexo é um gerador de sites estáticos em Node.js, parece ser uma alternativa super bacana ao Jekyll.

https://hexo.io/

**Comment by BielRibeiro** [comment]
O Harmonic também é bacana @fmoliveira 

https://github.com/JSRocksHQ/harmonic

**Comment by lnfnunes** [comment]
Antes de pensar na tecnologia de geração, penso que o primeiro passo seja criar um layout de referência com as características que o @fmoliveira comentou.
Já temos alguém olhando para isso ?

**Comment by rodolfoprr** [comment]
curti bastante o http://nodeschool.io/sanfrancisco/, por mim é ctrl c + ctrl v nele! huahuahua

**Comment by rodolfoprr** [comment]
curti bastante o http://nodeschool.io/hamburg/, por mim é ctrl c + ctrl v nele! huahuah

**Comment by fmoliveira** [comment]
Estes aqui também estão bacanas, bem minimalistas e objetivos:
 * http://nodeschool.io/toronto/
 * http://nodeschool.io/los-angeles/

Este ficou legal por usar as cores de Node.js, mas ainda gostei mais dos anteriores:
 * http://nodeschool.io/raleigh-durham/

**Comment by fmoliveira** [comment]
Legal @BielRibeiro , valeu pela dica!

**Comment by fmoliveira** [comment]
Com certeza @lnfnunes , o primeiro passo é criarmos o layout de referência mesmo.

Não sei se fazemos um novo layout ou apenas adaptamos o atual para incluir as informações faltantes.

O nosso [layout atual](http://nodeschool.io/campinas/) ficou bem popular apesar de ser um Bootstrap basicão. Foi forkado Em [San Francisco](http://nodeschool.io/sanfrancisco/), [Las Vegas](http://nodeschool.io/vegas/), [Kanpur](http://nodeschool.io/kanpur/) e [Florianópolis](http://nodeschool.io/florianopolis/#inicio).

Os forks de Vegas e Kanpur conseguiram adaptar bem novas informações e manter o layout minimalista, acho que ficaram bem legais.

Mas até agora o meu preferido foi o de [Los Angeles](http://nodeschool.io/los-angeles/), que conseguiu fornecer maior quantidade de informações em um layout bem clean.

Acho que se trabalharmos emcima do nosso da mesma forma que o pessoal de Las Vegas e Kanpur fizeram dá para incluir as informações faltantes numa boa com pouco esforço.

**Comment by victorperin** [comment]
Gostei bastante do final da página de [San Francisco](http://nodeschool.io/sanfrancisco/), com a foto de cada evento.
O que vocês acham?

**Comment by fmoliveira** [comment]
Também achei show de bola @victorperin !

Estou trabalhando no layout atual mesmo, logo atualizo para vocês verem o que acham. ;)

**Comment by fmoliveira** [comment]
Pessoal, dei uma atualizada bem de leve.

Coloquei um pouco mais de informações, a data e foto do último Meetup, e chamadas para estudantes e mentores. Mas as chamadas não estão muito destacadas, seria legal usar algum recurso visual para chamar mais atenção.

Caso alguém queira contribuir fique a vontade.

**Comment by rodolfoprr** [comment]
A imagem do Meetup ficou achatada aqui... tentei arrumar mas falhei miseravelmente, porque em resoluções diferentes da minha a imagem ficou "espremida" hauhuaha

**Comment by fmoliveira** [comment]
@rodolfoprr kkkkk, é porque as classes do carousel tem 500px de altura fixa. Precisa substituir o carousel por um jumbotron com height auto ou então criar uma nova classe com height auto !important. O último é mais fácil porque a classe carousel já está implementada para permitir adicionar tags img que se comportam como imagens de fundo, que eu acho que fica melhor do que definir background-images com URLs dinâmicas no CSS.

Na teoria este é o ponto de partida, mas fiz apenas um teste rápido no developer console, talvez ainda precise de mais ajustes...

**Comment by lnfnunes** [comment]
Mandei um PR ajustando a foto do meetup e também do banner superior.
Confira se está de acordo por favor.

ps: onde está o novo logo que votamos? Vou tentar montar os ajustes de layout q vc comentou no início.

**Comment by notnotgabriel** [comment]
![_nodeschool_cps_6](https://cloud.githubusercontent.com/assets/5247142/9215167/40265842-407d-11e5-85a3-27ff9e3c7802.jpg)
![nodeschool_cps_1](https://cloud.githubusercontent.com/assets/5247142/9215168/403c890a-407d-11e5-849b-5b4f67538bd1.jpg)
![nodeschool_cps_2](https://cloud.githubusercontent.com/assets/5247142/9215169/4064e7b0-407d-11e5-94f2-b1b4db89b2b5.jpg)
![nodeschool_cps_3](https://cloud.githubusercontent.com/assets/5247142/9215170/406cd894-407d-11e5-9bc1-418a245a1cd6.jpg)
![nodeschool_cps_4](https://cloud.githubusercontent.com/assets/5247142/9215172/406f83dc-407d-11e5-9831-eb2ef892b532.jpg)
![nodeschool_cps_5](https://cloud.githubusercontent.com/assets/5247142/9215173/40717ea8-407d-11e5-8458-6c1520638a93.jpg)
![nodeschool_cps_6](https://cloud.githubusercontent.com/assets/5247142/9215171/406e2e2e-407d-11e5-9e29-d3a295bc4633.jpg)

**Comment by notnotgabriel** [comment]
Não lembro se definimos um, mas estão aí todos os que mostramos aquele dia =)

**Comment by notnotgabriel** [comment]
Acho que teve algum ajustes na verdade.
@rodolfoprr o Lucas chegou a te passar aquele que ele ajustou? Eu vi ele mexendo esses dias.
Vou ver com ele amanhã.

**Comment by lnfnunes** [comment]
Se não me falhe a memória o escolhido foi [esse](https://cloud.githubusercontent.com/assets/5247142/9215172/406f83dc-407d-11e5-9831-eb2ef892b532.jpg) com ajustes de cor (igual do node) e simplificação das linhas.
Vou esperar vcs verificarem com o designer ;-)
**VALEU @BielRibeiro !!!**

**Comment by notnotgabriel** [comment]
@lnfnunes vejo com ele e passo por aqui amanha. É nois.

**Comment by fmoliveira** [comment]
Obrigado @lnfnunes , já aceitei o seu PR, ficou ótimo!

Isso mesmo, o logo escolhido na votação foi este que vc linkou com os ajustes mencionados.

Valeu @BielRibeiro ! ;)

**Comment by fmoliveira** [comment]
Acabei de incluir o logotipo oficial do NodeSchool Campinas no site, mas ainda precisaremos de ajustes na imagem de fundo para dar destaque ao logotipo.

**Comment by fmoliveira** [comment]
O site está bacana por enquanto. Estou fechando.

Obrigado a todos pelas ideias e pelas contribuições!
