### ISSUE TITLE
Inclusão no hexdex

### ISSUE THREAD

**Issue by fmoliveira** [nodeschool/campinas#8]
http://nodeschool.io/hexdex.html

**Comment by fmoliveira** [comment]
Primeiro precisa remover o padding do nosso logotipo.

**Comment by victorperin** [comment]
Atualizei no PR #9. Da uma olhada se ta tudo certo, porque fiz pelo inkscape, no fedora...

**Comment by fmoliveira** [comment]
Obrigado @victorperin ! Ficou ótimo! ;)

**Comment by fmoliveira** [comment]
PR criado em nodeschool/nodeschool.github.io#412.

**Comment by fmoliveira** [comment]
Atualizado. :)

Valeu @victorperin pela força!

**Comment by victorperin** [comment]
Aewww! :)
